services:
  postgres:
    image: postgres:16
    container_name: sky_postgres
    environment:
      POSTGRES_USER: sky
      POSTGRES_PASSWORD: sky123
      POSTGRES_DB: sky_hr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sky_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sky_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@skytime.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - sky_network
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: sky_redis
    ports:
      - "6379:6379"
    networks:
      - sky_network

volumes:
  pgdata:
  pgadmin_data:

networks:
  sky_network:
    driver: bridge
